# Generated by Django 4.2.10 on 2024-02-22 13:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, default='coins/default.png', null=True, upload_to='coins/')),
            ],
            options={
                'unique_together': {('name', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, default='exchanges/default.png', null=True, upload_to='exchanges/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coins', models.ManyToManyField(to='api.coin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=20, max_digits=40)),
                ('purchase_price', models.DecimalField(decimal_places=20, max_digits=40)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.coin')),
                ('exchange', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exchange')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='api.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='CoinExchangeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=20, max_digits=40)),
                ('volume', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True)),
                ('prev_price_24h', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coin')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exchange')),
            ],
            options={
                'unique_together': {('coin', 'exchange', 'date')},
            },
        ),
    ]
