# Generated by Django 4.2.10 on 2024-02-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinexchangeinfo',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=40, null=True),
        ),
    ]
