# Generated by Django 5.0.2 on 2024-02-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='logo',
            new_name='icon',
        ),
    ]
