# Generated by Django 4.2.10 on 2024-02-23 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_coinexchangeinfo_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='coins',
        ),
        migrations.CreateModel(
            name='WatchlistCoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.coin')),
                ('exchange', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exchange')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='api.watchlist')),
            ],
        ),
    ]
