# Generated by Django 4.2.10 on 2024-03-03 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_watchlist_name_alter_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioholding',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coin'),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='created',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='watchlistcoin',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coin'),
        ),
        migrations.AlterField(
            model_name='watchlistcoin',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlistcoins', to='api.watchlist'),
        ),
    ]
