# Generated by Django 4.2.10 on 2024-03-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistcoin',
            name='exchange',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.exchange'),
            preserve_default=False,
        ),
    ]
