# Generated by Django 4.2.10 on 2024-03-25 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_portfolioholding_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinexchangeinfo',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
